### ISSUE TITLE
使用 go mod 的方式， 报错

### ISSUE THREAD

**Issue by guzzsek** [go-kratos/prometheus#1]
➜  kratos-demo go get github.com/go-kratos/prometheus
go: github.com/go-kratos/prometheus upgrade => v0.0.0-20210222132159-fb83c1d7a441
go get: github.com/go-kratos/prometheus@v0.0.0-20210222132159-fb83c1d7a441 requires
        github.com/go-kratos/kratos/v2@v2.0.0-20210111161948-bd8b6f1fb597/go.mod: verifying module: github.com/go-kratos/kratos/v2@v2.0.0-20210111161948-bd8b6f1fb597/go.mod: reading https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/go-kratos/kratos/v2@v2.0.0-20210111161948-bd8b6f1fb597: 410 Gone
        server response: not found: github.com/go-kratos/kratos/v2@v2.0.0-20210111161948-bd8b6f1fb597: invalid version: unknown revision bd8b6f1fb597

**Comment by tonybase** [comment]
#2
